version: '3.7'
services:
  bot:
    build: .
    container_name: splinterlands_bot
    image: splinterlands-bot
    ports:
      - 10001:80
    volumes:
      - ${PWD}/.env:/app/.env
    networks:
      - splinterlands_main
networks:
  splinterlands_main: